In [1]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.9.0+cu130
True


#### 标量
##### （标量由只有一个元素的张量表示）

In [2]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

#### 向量
##### （向量为标量值组成的列表，其中标量值成为向量的元素或分量）

`列向量是向量的默认方向`

In [3]:
# 通过一维张量表示向量
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
x[3]

tensor(3)

#### 长度、维度和形状

In [5]:
len(x)

4

In [6]:
x.shape

torch.Size([4])

In [7]:
A = torch.arange(24).reshape(4, 6)
A

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [8]:
A.T

tensor([[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20],
        [ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]])

#### 对称矩阵

In [9]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [10]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

#### 张量

### `向量是标量的推广，矩阵是向量的推广`

In [11]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [12]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

#### 哈达玛积（逐元素相乘）

In [13]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

#### 矩阵点乘

In [14]:
C = torch.arange(8, dtype=torch.float32).reshape(4, 2)
#法一
A @ C

tensor([[ 28.,  34.],
        [ 76.,  98.],
        [124., 162.],
        [172., 226.],
        [220., 290.]])

In [15]:
#法二
D = torch.mm(A, C)
D

tensor([[ 28.,  34.],
        [ 76.,  98.],
        [124., 162.],
        [172., 226.],
        [220., 290.]])

In [16]:
#法三
E = torch.matmul(A, C)
E

tensor([[ 28.,  34.],
        [ 76.,  98.],
        [124., 162.],
        [172., 226.],
        [220., 290.]])

In [17]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 降维

In [18]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [19]:
print(A)
A.shape, A.sum()

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(torch.Size([5, 4]), tensor(190.))

In [20]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [21]:
A.sum(axis=[0, 1])

tensor(190.)

In [22]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [23]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

#### 非降维求和

In [24]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [25]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [26]:
A.cumsum(axis=0)        #不降维但求和了

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

#### 点积

In [27]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [28]:
x * y, torch.sum(x * y)

(tensor([0., 1., 2., 3.]), tensor(6.))

#### 矩阵-向量积

### `使用张量表示矩阵-向量积，我们使用mv函数`

In [29]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

#### 矩阵-矩阵乘法

In [30]:
# 矩阵乘法
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

#### 范数（***）

In [31]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [32]:
torch.abs(u).sum()

tensor(7.)

In [33]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

### 作业